apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: discourse-local-pvc
  labels:
    app: web-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
        storage: 10Gi