apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgsql-local-pvc
  labels:
    app: pgsql-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi