apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
data:
  dbUsername: YWRtaW4=
  dbPassword: YWRtaW45MA==
  smtpUsername: aHViZXJ0bmFuZzIwMTdAZ21haWwuY29t
  smtpPassword: ZzJYVERKYXdQbjRPWWpteA==
